/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package finalpoo;

/**
 *
 * @author Sammy
 */
public class Borrar_Datos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingresar_Datos
     */
    public Borrar_Datos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nombre_Field = new javax.swing.JTextField();
        Telefono_Field = new javax.swing.JTextField();
        Cedula_Field = new javax.swing.JTextField();
        Ingresar_Button = new javax.swing.JButton();
        Borrar_Button = new javax.swing.JButton();
        Salir_Button = new javax.swing.JButton();

        setTitle("Borrado Datos");

        jLabel1.setText("Nombre");

        jLabel2.setText("Telefono");

        jLabel3.setText("Cedula");

        Ingresar_Button.setText("Eliminar");
        Ingresar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_ButtonActionPerformed(evt);
            }
        });

        Borrar_Button.setText("Borrar");
        Borrar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar_ButtonActionPerformed(evt);
            }
        });

        Salir_Button.setText("Salir");
        Salir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono_Field)
                                    .addComponent(Cedula_Field)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Ingresar_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Borrar_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Salir_Button)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Telefono_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cedula_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresar_Button)
                    .addComponent(Borrar_Button)
                    .addComponent(Salir_Button))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Borrar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar_ButtonActionPerformed
        Nombre_Field.setText("");
        Cedula_Field.setText("");
        Telefono_Field.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_Borrar_ButtonActionPerformed

    private void Ingresar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_ButtonActionPerformed
        String nombre = Nombre_Field.getText();
        String cedula = Cedula_Field.getText();
        String telefono = Telefono_Field.getText();
        Write_File.deleteline(nombre,cedula,telefono);        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_ButtonActionPerformed

    private void Salir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_ButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar_Button;
    private javax.swing.JTextField Cedula_Field;
    private javax.swing.JButton Ingresar_Button;
    private javax.swing.JTextField Nombre_Field;
    private javax.swing.JButton Salir_Button;
    private javax.swing.JTextField Telefono_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
