/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package finalpoo;

import java.util.ArrayList;

/**
 *
 * @author Sammy
 */
public class Consultar_Nombre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar_Nombre
     */
    public Consultar_Nombre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cedula_Field = new javax.swing.JTextField();
        Nombre_Field = new javax.swing.JTextField();
        Consultar_Button = new javax.swing.JButton();
        Borrar_Button = new javax.swing.JButton();
        Salir_Button = new javax.swing.JButton();

        setTitle("Consulta Nombres");

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        Consultar_Button.setText("Consultar");
        Consultar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_ButtonActionPerformed(evt);
            }
        });

        Borrar_Button.setText("Borrar");
        Borrar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar_ButtonActionPerformed(evt);
            }
        });

        Salir_Button.setText("Salir");
        Salir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(Nombre_Field))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(Cedula_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consultar_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Borrar_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Salir_Button)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Cedula_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar_Button)
                    .addComponent(Borrar_Button)
                    .addComponent(Salir_Button))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Consultar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_ButtonActionPerformed
        for(int i = 0;i < search.size(); i++){
            ArrayList<String> curr = search.get(i);
            if(curr.get(1).equals(Cedula_Field.getText())){
                Nombre_Field.setText(curr.get(0));
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Consultar_ButtonActionPerformed

    private void Borrar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar_ButtonActionPerformed
        Nombre_Field.setText("");
        Cedula_Field.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Borrar_ButtonActionPerformed

    private void Salir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_ButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Salir_ButtonActionPerformed

    private ArrayList<ArrayList> search = Read_File.create_search_array();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar_Button;
    private javax.swing.JTextField Cedula_Field;
    private javax.swing.JButton Consultar_Button;
    private javax.swing.JTextField Nombre_Field;
    private javax.swing.JButton Salir_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
