/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalpoo;

import javax.swing.JFrame;

/**
 *
 * @author Sammy
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salir_item = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Ingresar_Menu = new javax.swing.JMenu();
        Ingresar_Item = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Consultar_Menu = new javax.swing.JMenu();
        Telefono_Item = new javax.swing.JMenuItem();
        Nombre_Item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        Salir_item.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Salir_item.add(jMenuItem1);

        jMenuBar1.add(Salir_item);

        Ingresar_Menu.setText("Ingreso");

        Ingresar_Item.setText("Ingresar Datos");
        Ingresar_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_ItemActionPerformed(evt);
            }
        });
        Ingresar_Menu.add(Ingresar_Item);

        jMenuBar1.add(Ingresar_Menu);

        jMenu1.setText("Borrar");

        jMenuItem2.setText("Borrar Datos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        Consultar_Menu.setText("Consulta");

        Telefono_Item.setText("Consultar Telefono");
        Telefono_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telefono_ItemActionPerformed(evt);
            }
        });
        Consultar_Menu.add(Telefono_Item);

        Nombre_Item.setText("Consultar Nombre");
        Nombre_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_ItemActionPerformed(evt);
            }
        });
        Consultar_Menu.add(Nombre_Item);

        jMenuBar1.add(Consultar_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Ingresar_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_ItemActionPerformed
        Ingresar_Datos ing = new Ingresar_Datos();
        jDesktopPane1.add(ing);
        ing.setClosable(true);
        ing.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_ItemActionPerformed

    private void Telefono_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono_ItemActionPerformed
        Consultar_Telefono tel = new Consultar_Telefono();
        jDesktopPane1.add(tel);
        tel.setClosable(true);
        tel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Telefono_ItemActionPerformed

    private void Nombre_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_ItemActionPerformed
        Consultar_Nombre nom = new Consultar_Nombre();
        jDesktopPane1.add(nom);
        nom.setClosable(true);
        nom.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_ItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Borrar_Datos borr = new Borrar_Datos();
        jDesktopPane1.add(borr);
        borr.setClosable(true);
        borr.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultar_Menu;
    private javax.swing.JMenuItem Ingresar_Item;
    private javax.swing.JMenu Ingresar_Menu;
    private javax.swing.JMenuItem Nombre_Item;
    private javax.swing.JMenu Salir_item;
    private javax.swing.JMenuItem Telefono_Item;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
